name: pyintro
channels:
  - conda-forge
dependencies:
  - tornado<6
  - python
  - numpy
  - scipy
  - pandas
  - xlrd
  - xarray
  - holoviews
  - matplotlib
  - bokeh
  - jupyterlab
  - selenium

# jupyter labextension install @jupyterlab/toc @pyviz/jupyterlab_pyviz
